import { MigrationInterface, QueryRunner } from "typeorm";

export class default1685375479549 implements MigrationInterface {
    name = 'default1685375479549'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "ids" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "idExcluido" uuid NOT NULL, "idExclusor" uuid NOT NULL, CONSTRAINT "PK_b50be43990162fd573c7f866477" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "ids"`);
    }

}
